name = 'Pehtheme Hugo'
license = 'MIT'
licenselink = 'https://github.com/bytecascade11'
description = 'ByteCascade Technology delivers the latest tech news, gadget Opinions, Android updates, and in-depth guides to keep you informed and ahead in the digital world.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/fauzanmy/pehtheme-hugo'

# If you have a running demo of the theme
demosite = 'https://pehtheme-hugo.netlify.app/'

# Taxonomy terms
tags = ['blog', 'responsive', 'light', 'tailwindcss']
features = ['tailwindcss', 'two-column', 'sidebar', 'horizontal-menu']

# If the theme has multiple authors

[author]
  name = 'iSamuel'
  homepage = 'https://pin.it/78p5ZcbNJ'
